/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Automovil;
import javax.swing.JOptionPane;

/**
 *
 * @author Moon
 */
public class FRM_Automovil extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Automovil
     */
    Controlador_FRM_Automovil controlador;
    
    public FRM_Automovil() 
    {
        initComponents();
        controlador=new Controlador_FRM_Automovil(this);
        this.gUI_Botones1.agregarEventos(controlador);
    }
    
    public String[] devolverInformacion()
    {
        return this.gUI_Informacion1.devolverInformacion();
    }
    public void mostrarInformacion(String arreglo[])
    {
        this.gUI_Informacion1.mostrarInformacion(arreglo);
    }
    public String devolverNumeroRegistro()
    {
        return this.gUI_Informacion1.devolverNumeroRegistro();
    }
    
    public void mensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null,mensaje);
    }
    public void noEncontroCodigo()
    {
        this.gUI_Botones1.noEncontroCodigo();
    }
    public void encontroCodigo()
    {
        this.gUI_Botones1.noEncontroCodigo();
    }
    public void estadoInicial()
    {
        this.gUI_Botones1.estadoInicial();
    }
    public void agrego()
    {
        this.gUI_Informacion1.agregaText();
    }
    public void encontroBuscarText()
    {
     
        this.gUI_Informacion1.encontroBuscarText();
    }
    public void encontroBuscar()
    {
        this.gUI_Botones1.encontroBuscar();
    }
    public void estadoInicialText()
    {
        this.gUI_Informacion1.estadoInicialText();
    }
    public void noEncontroCodigotext()
    {
        this.gUI_Informacion1.noEncontroCodigoText();
    }
    public void limpiarText()
    {
        this.gUI_Informacion1.limpiarText();
    }
    public void limpiarTextModifica()
    {
        this.gUI_Informacion1.limpiarTextModifica();
    }
    public void aumentarCodigo(String codigo)
    {
        this.gUI_Informacion1.aumentarCodigo(codigo);
    }
//    public void aumentarCodigo()
//    {
//        this.gUI_Informacion1.encontroCodigoText();
//    }
//    public void encontroCodigoText()
//    {
//        this.gUI_Informacion1.encontroCodigoText();
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_Botones1 = new Vista.GUI_Botones();
        gUI_Informacion1 = new Vista.GUI_Informacion();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_Informacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(gUI_Informacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Automovil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_Informacion gUI_Informacion1;
    // End of variables declaration//GEN-END:variables
}
