/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Moon
 */
public class GUI_Informacion extends javax.swing.JPanel {

    /**
     * Creates new form GUI_Informacion
     */
    public GUI_Informacion() {
        initComponents();
        estadoInicialText();
    }

    public String[] devolverInformacion() 
    {
        String arreglo[];
        arreglo=new String[4];
        
        arreglo[0]=this.jt_NumeroRegistro.getText();
        arreglo[1]=this.jt_NombreDueño.getText();
        arreglo[2]=this.jt_CedulaDueño.getText();
        arreglo[3]=this.jt_PlacaAutomovil.getText();
        
        return arreglo;
    }
    
    public void mostrarInformacion(String arreglo[])
    {
        this.jt_NombreDueño.setText(arreglo[0]);
        this.jt_CedulaDueño.setText(arreglo[1]);
        this.jt_PlacaAutomovil.setText(arreglo[2]);
    }
    
    public void aumentarCodigo(String codigo)
    {
        this.jt_NumeroRegistro.setText(codigo);
    }
            
    public String devolverNumeroRegistro()
    {
        return this.jt_NumeroRegistro.getText();
    }
    public void estadoInicialText()
    {
        this.jt_NumeroRegistro.setEnabled(false);
        this.jt_CedulaDueño.setEnabled(false);
        this.jt_NombreDueño.setEnabled(false);
        this.jt_PlacaAutomovil.setEnabled(false);
    }
    public void encontroBuscarText()
    {
        this.jt_NumeroRegistro.setEnabled(false);
        this.jt_CedulaDueño.setEnabled(true);
        this.jt_NombreDueño.setEnabled(true);
        this.jt_PlacaAutomovil.setEnabled(true);
    }
    public void noEncontroCodigoText()
    {
        this.jt_NumeroRegistro.setEnabled(false);
        this.jt_NombreDueño.setEnabled(true);
        this.jt_PlacaAutomovil.setEnabled(true);
        this.jt_CedulaDueño.setEnabled(true);
    }
    public void agregaText()
    {
        this.jt_NumeroRegistro.setEnabled(true);
        this.jt_NombreDueño.setEnabled(true);
        this.jt_PlacaAutomovil.setEnabled(true);
        this.jt_CedulaDueño.setEnabled(true);
    }
    public void limpiarText()
    {   
        this.jt_NombreDueño.setText("");
        this.jt_PlacaAutomovil.setText("");
        this.jt_CedulaDueño.setText("");
    }
    
    public void limpiarTextModifica()
    {   
        this.jt_NumeroRegistro.setText("");
        this.jt_NombreDueño.setText("");
        this.jt_PlacaAutomovil.setText("");
        this.jt_CedulaDueño.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_NumeroRegistro = new javax.swing.JLabel();
        jl_NombreDueño = new javax.swing.JLabel();
        jl_CedulaDueño = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jt_NumeroRegistro = new javax.swing.JTextField();
        jt_NombreDueño = new javax.swing.JTextField();
        jt_CedulaDueño = new javax.swing.JTextField();
        jt_PlacaAutomovil = new javax.swing.JTextField();

        jl_NumeroRegistro.setText("Número de registro");

        jl_NombreDueño.setText("Nombre del dueño");

        jl_CedulaDueño.setText("Cédula del dueño");

        jLabel4.setText("Placa del automóvil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_NumeroRegistro)
                    .addComponent(jl_NombreDueño)
                    .addComponent(jl_CedulaDueño)
                    .addComponent(jLabel4))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jt_NumeroRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jt_NombreDueño)
                    .addComponent(jt_CedulaDueño)
                    .addComponent(jt_PlacaAutomovil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NumeroRegistro)
                    .addComponent(jt_NumeroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NombreDueño)
                    .addComponent(jt_NombreDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_CedulaDueño)
                    .addComponent(jt_CedulaDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jt_PlacaAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jl_CedulaDueño;
    private javax.swing.JLabel jl_NombreDueño;
    private javax.swing.JLabel jl_NumeroRegistro;
    private javax.swing.JTextField jt_CedulaDueño;
    private javax.swing.JTextField jt_NombreDueño;
    private javax.swing.JTextField jt_NumeroRegistro;
    private javax.swing.JTextField jt_PlacaAutomovil;
    // End of variables declaration//GEN-END:variables
}
